# Generated by Django 5.2.5 on 2025-09-30 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_note_updated_at_note_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='note',
            name='version',
        ),
    ]
